name: Docker Image CI

on:
  workflow_run:
    workflows: ["Spring Boot CI"]
    types:
      - completed

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Grant execute permission to Maven Wrapper
        run: chmod +x mvnw

      - name: Build the app with Maven
        run: ./mvnw clean package -DskipTests

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # change if your region is different

      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t authentication-service:latest .

      # Tag Docker image for ECR
      - name: Tag Docker image
        run: |
          docker tag authentication-service:latest 575108922870.dkr.ecr.us-east-1.amazonaws.com/authentication-service

      # Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push 575108922870.dkr.ecr.us-east-1.amazonaws.com/authentication-service
